### ISSUE TITLE
how to integrate mailboxer with rails5

### ISSUE THREAD

**Issue by ajazshaik** [mailboxer/mailboxer#432] opened 2016-08-01 05:26 UTC

**Comment by deivid-rodriguez** [comment] 2016-08-04 09:55
I don't think there's any special considerations for Rails 5.

I'd close this since it's just a support question.

**Comment by alexung** [comment] 2016-10-04 21:48
@ajazshaik I'm currently using rails 5 and it works for me.

**Comment by bodrovis** [comment] 2016-10-17 20:11
I can confirm that it does work with Rails 5. Here is an article about Mailboxer https://www.sitepoint.com/messaging-rails-mailboxer/

**Comment by codered** [comment] 2016-11-14 20:21
I am using it in rails 5, you can close this thread.

**Comment by jasdeepsingh** [comment] 2017-02-13 03:33
Works well with Rails 5 for me too.

**Closed** 2017-02-13 15:14 UTC
