### ISSUE TITLE
Multiple attachments are allowing in Mailboxer?

### ISSUE THREAD

**Issue by sathishcel** [mailboxer/mailboxer#417] opened 2016-05-27 11:36 UTC
Tell me that Mailboxer is allowing Multiple attachment or not?

I am trying 
 <%= f.file_field "attachment" , class:"form-control", multiple: true %> But it not allowing at same time I can attach single file and send email.

**Comment by caJaeger** [comment] 2016-07-19 11:30
https://github.com/mailboxer/mailboxer/issues/344

**Comment by jcoyne** [comment] 2016-07-19 11:42
Closed duplicate of #344

**Closed by jcoyne** 2016-07-19 11:42 UTC
